### ISSUE TITLE
Rename "app_prototype" directories 

### ISSUE THREAD

**Issue by timriley** [carbonfive/raygun#132]
We have a application skeleton project that we're using raygun to install. This project uses `app_prototype` in some directory paths, since it follows a more Ruby-conventional, less Rails-y approach to the directory structure (e.g. `lib/app_prototype/some_file.rb`). We'd obviously like these directories to be renamed to match the provided name of the project when raygun is installing it.

Would you be prepared to consider a PR that adds support for renaming directories? Wanted to check before I went about implementing it.

Thanks! Love your tool.

**Comment by timriley** [comment]
Oh, to make this thorough, I realise we'd want to do the same kind of renaming for any files with "app_prototype" in their name.

**Comment by christiannelson** [comment]
@timriley Thanks for the report.

Your app prototype has directories and files that you want to be renamed when raygun copies and does it's mass renaming?

That should be pretty easy to implement. Check out https://github.com/carbonfive/raygun/blob/master/lib/raygun/raygun.rb#L109 for where such a thing could happen. I would use `find` with the `-exec` option, though given unix, there may be other solutions.

If you create a PR, be sure to test it under Mac and Linux, since we want raygun to work under both envs. Raygun itself doesn't have any specs, so by test I mean manually.

**Comment by timriley** [comment]
Thanks @christiannelson! Just submitted something to you now.

**Comment by eskfung** [comment]
I believe https://github.com/carbonfive/raygun/pull/133 totally resolves the issue. Thanks again!
