### ISSUE TITLE
Raygun uses the ruby version of the context in which raygun is run, rather than using the template app's declared ruby version

### ISSUE THREAD

**Issue by eskfung** [carbonfive/raygun#167]
While reviewing a recent PR (https://github.com/carbonfive/raygun/pull/163), I noticed that Raygun wanted to specify usage of Ruby 2.6.5, even though the raygun-rails template has [a tagged version](https://github.com/carbonfive/raygun-rails/releases/tag/v1.9.4) that supports Ruby 3.0.x. After digging in, it looks like Raygun will use the ruby version  _of the environment in which Raygun is run_, rather than reading from the template app.

Reference: https://github.com/carbonfive/raygun/blob/main/lib/raygun/raygun.rb#L32-L33

**Comment by mattbrictson** [comment]
I think this is intentional and it mimics how `rails new` works.

What makes the current behavior awkward, in my opinion, is that the raygun repo and the raygun-rails repo _both_ have a `.ruby-version` file. So if you are developing raygun and testing it locally, it is now ambiguous which version file should be honored.

My recommended solution would be to _remove_ the `.ruby-version` file from the raygun repo. That way when you test raygun "from source", you'll be getting the same behavior as a general user does if they install the gem. That is, it will generate the app using your default version of ruby, whatever that is.

What do you think?

**Comment by eskfung** [comment]
Totally makes sense to me!
